### ISSUE TITLE
[Feature Request] The ability to specify folders and files along with arguments.

### ISSUE THREAD

**Issue by Avaray** [PrestaShopCorp/github-action-php-lint#16]
At the moment, you can only exclude folders. It would be useful to have the option to select specific files/folders to lint, as well as the ability to add arguments to the file being linted.

I see it as:

```yml
- name: PHP 8.3 syntax check
  uses: PrestaShopCorp/github-action-php-lint/8.3@master
  with:
    folders: ['src', 'tests']
    files: ['file.php argv1=asd argv2=zxc', 'file2.php']
```
